// <auto-generated />
using System;
using KeepFocus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KeepFocus.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KeepFocus.Domain.Entities.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_boards");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_boards_user_id");

                    b.ToTable("boards", (string)null);
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cards");

                    b.HasIndex("ListId", "Position")
                        .HasDatabaseName("ix_cards_list_id_position");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.Checklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_checklists");

                    b.HasIndex("CardId")
                        .HasDatabaseName("ix_checklists_card_id");

                    b.ToTable("checklists", (string)null);
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("uuid")
                        .HasColumnName("checklist_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_checked");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_checklist_items");

                    b.HasIndex("ChecklistId")
                        .HasDatabaseName("ix_checklist_items_checklist_id");

                    b.ToTable("checklist_items", (string)null);
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.FocusSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccumulatedSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("accumulated_sec");

                    b.Property<Guid?>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTime>("LastResumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_resumed_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("mode");

                    b.Property<int>("PlannedDuration")
                        .HasColumnType("integer")
                        .HasColumnName("planned_duration_sec");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_focus_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_focus_sessions_user_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_focus_sessions_user_active")
                        .HasFilter("status = 'Active'");

                    b.ToTable("focus_sessions", (string)null);
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.List", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_lists");

                    b.HasIndex("BoardId", "Position")
                        .HasDatabaseName("ix_lists_board_id_position");

                    b.ToTable("lists", (string)null);
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.SessionBreak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BreakType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("break_type");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_sec");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_session_breaks");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_session_breaks_session_id");

                    b.ToTable("session_breaks", (string)null);
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.TabEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_sec");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_tab_events");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_tab_events_session_id");

                    b.ToTable("tab_events", (string)null);
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.Card", b =>
                {
                    b.HasOne("KeepFocus.Domain.Entities.List", null)
                        .WithMany("_cards")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cards_lists_list_id");
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.Checklist", b =>
                {
                    b.HasOne("KeepFocus.Domain.Entities.Card", null)
                        .WithMany("_checklists")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checklists_cards_card_id");
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.ChecklistItem", b =>
                {
                    b.HasOne("KeepFocus.Domain.Entities.Checklist", null)
                        .WithMany("_items")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_items_checklists_checklist_id");
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.List", b =>
                {
                    b.HasOne("KeepFocus.Domain.Entities.Board", null)
                        .WithMany("_lists")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lists_boards_board_id");
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.SessionBreak", b =>
                {
                    b.HasOne("KeepFocus.Domain.Entities.FocusSession", null)
                        .WithMany("_breaks")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_breaks_focus_sessions_session_id");
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.TabEvent", b =>
                {
                    b.HasOne("KeepFocus.Domain.Entities.FocusSession", null)
                        .WithMany("_tabEvents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tab_events_focus_sessions_session_id");
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.Board", b =>
                {
                    b.Navigation("_lists");
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.Card", b =>
                {
                    b.Navigation("_checklists");
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.Checklist", b =>
                {
                    b.Navigation("_items");
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.FocusSession", b =>
                {
                    b.Navigation("_breaks");

                    b.Navigation("_tabEvents");
                });

            modelBuilder.Entity("KeepFocus.Domain.Entities.List", b =>
                {
                    b.Navigation("_cards");
                });
#pragma warning restore 612, 618
        }
    }
}
